name: Build APK (unsigned)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept all SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install required SDK packages
        run: sdkmanager "build-tools;34.0.0" "platforms;android-34" "platform-tools"

      - name: Build APK unsigned
        run: ./gradlew assembleRelease

      - name: Upload APK (unsigned)
        uses: actions/upload-artifact@v4
        with:
          name: App-release-unsigned
          path: app/build/outputs/apk/release/app-release-unsigned.apk
