name: Build APK from ZIP (TFTOverlay V3)

on:
  workflow_dispatch:       # Cho phép chạy thủ công
  push:
    branches: [ main ]     # Commit vào main sẽ tự build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Cài Android SDK + license + các gói cần thiết
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true
          packages: |
            build-tools;34.0.0
            platforms;android-34
            platform-tools

      # Giải nén project từ file ZIP ở root repo
      - name: Unzip project
        run: |
          unzip -q TFTOverlay_V3_Blitz.zip -d src
          mv src/TFTOverlay/* .
          ls -la
          ls -la app || true

      - name: Grant Gradle wrapper permission
        run: chmod +x ./gradlew

      # Build nhanh bản debug (chưa ký). Muốn release thì đổi assembleDebug -> assembleRelease
      - name: Build debug APK
        run: ./gradlew assembleDebug

      # Tải APK ở mục Artifacts
      - name: Upload APK (debug)
        uses: actions/upload-artifact@v4
        with:
          name: TFTOverlay-debug-APK
          path: app/build/outputs/apk/debug/*.apk
